[package]
name = "inaturalist-oauth"
version = "0.1.0"
edition = "2021"

[dependencies]
oauth2 = "4.3.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2.3.1"
opener = "0.6"
log = "0.4.20"
httparse = "1.10.1"
